# Generated by Django 5.0.6 on 2024-11-08 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_age_userprofile_sex_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_join',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
