# Generated by Django 5.0.6 on 2024-11-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_date_join_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deleted_folders',
            field=models.TextField(blank=True, null=True),
        ),
    ]
