# Generated by Django 5.0.6 on 2024-11-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userprofile_deleted_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=255, null=True, verbose_name='status'),
        ),
    ]
